### PR TITLE
fix: indent consistency of multiline-format

### LINKED ISSUE #95: need to format indent for multi-fields-object in dictionary
# As is
* Indent of object with multifields in dectionary is the following.
The indent depends on **keyname's length**.
```
"dog-1": Dog(
    dict: [
        "apple": AppleJuice(
                              price: 100,
                              sale: true
                       ) ,
        "pi": PI(
                     price: 100,
                     sale: true
        ) 
    ]
),
```

# To be
It should depends on "Debug.Option.indent".
It makes fields be easier to read.

```
"dog-1": Dog(
    dict: [
        "apple": AppleJuice(
              price: 100,
              sale: true
        ) ,
        "pi": PI(
              price: 100,
              sale: true
         ) 
    ]
),
```

### PR DESCRIPTION
**Pull request by YusukeHosonuma**
resolved #95 

## TODO
- [x] fix indent consistency
- [x] refactor
- [x] update Example
- [x] update README

### CODE REVIEW

File: Sources/Core/Formatter/MultilineFormatter.swift [hunk 1]
```diff
@@ -6,44 +6,50 @@
 //
 
 class MultilineFormatter: PrettyFormatter {
-    private let option: Debug.Option
+    private let indentSize: Int
```
Comment (YusukeHosonuma) [inline Sources/Core/Formatter/MultilineFormatter.swift:9]: Refactor: `MultilineFormatter` depends on `indentSize` instead of `Debug.Option`.

File: Sources/Core/Formatter/MultilineFormatter.swift [hunk 2]
```diff
@@ -6,44 +6,50 @@
...
 
-    init(option: Debug.Option) {
-        self.option = option
+    init(indentSize: Int) {
```
Comment (YusukeHosonuma) [inline Sources/Core/Formatter/MultilineFormatter.swift:11]: Refactor: rename to `indentSize` from `indent` because the name `indent` is ambiguous.

File: Sources/Core/Formatter/MultilineFormatter.swift [hunk 3]
```diff
@@ -6,44 +6,50 @@
...
+        self.indentSize = indentSize
     }
 
     func collectionString(elements: [String]) -> String {
-        """
+        let contents = elements.joined(separator: ",\n")
```
Comment (YusukeHosonuma) [inline Sources/Core/Formatter/MultilineFormatter.swift:16]: Refactor: for consistency of code-style.

File: Tests/SwiftPrettyPrintTests/Core/Formatter/MultilineFormatterTests.swift [hunk 4]
```diff
@@ -38,69 +39,125 @@ class MultilineFormatterTests: XCTestCase {
...
-                                    first: true),
-                             2: "Two"
-                         ]
-                         """)
+        func f(indentSize: Int, keysAndValues: [(String, String)]) -> String {
+            let formatter = MultilineFormatter(indentSize: indentSize)
+            return formatter.dictionaryString(keysAndValues: keysAndValues)
+        }
+        
+        assert(to: f, with: assertEqualLines) {
```
Comment (YusukeHosonuma) [inline Tests/SwiftPrettyPrintTests/Core/Formatter/MultilineFormatterTests.swift:47]: Introduce parameterized-test. But not so easy to read?  😅

File: Example/SwiftPrettyPrintExample/Source/AppDelegate.swift [hunk 5]
```diff
@@ -29,24 +29,32 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
...
+        //     id: "pochi",
+        //     price: 10.0,
+        //     name: "ポチ"
+        //   ),
+        //   "two": Dog(
+        //     id: "pochi",
+        //     price: 10.0,
+        //     name: "ポチ"
+        //   )
         // ]
```
Comment (YusukeHosonuma) [inline Example/SwiftPrettyPrintExample/Source/AppDelegate.swift:58]: I got perfectly expected behavior in Example app :)

**Review by po-miyasaka — APPROVED** [review]
lgtm!
